### PR TITLE
readme: Initialize.

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by BlueFlo0d** [comment]
I'm not sure if CCL does any typecheck -- on my machine it doesn't seem to do any and `probe-ftype` is basically an n-op. Can you confirm?

**Comment by Ambrevar** [comment]
Good catch.  CCL does support compile-time type-checking though, it's just that the `declare` in probe-ftype does not do the trick here.

See this CCL session:

```lisp
> (declaim (ftype (function (number) number) foof))
> (defun foof (n) (* 2 n))
> (compile nil (lambda () (foof "foo")))
;Compiler warnings :
;   In an anonymous lambda form: Type declarations violated in (THE NUMBER "foo")
#<Anonymous Function #x302000E24CBF>
NIL
NIL
```

**Comment by BlueFlo0d** [comment]
Interesting. Let me try to figure out a `probe-ftype` that also works on CCL.

**Comment by Ambrevar** [comment]
I've updated the readme to remove CCL mention for now.
This should be OK to merge, we can take care of CCL in a separate issue.

**Comment by BlueFlo0d** [comment]
It seems that it's hard to get CCL check a function definition. Probably because built-in functions (e.g. `*`) do not have type declarations?
```
> (declaim (ftype (function (string) string) foof))
> (defun foof (n) (* 2 n))
> (compile nil (lambda () (foof "foo"))) ;; no error
> (compile nil (lambda () (* 2 "foo"))) ;; no error
```
Looks kind of hopeless...

**Pull request merged**
